# NOTE
The material in this notebook is strongly influenced by a linear algebra tutorial by Aurelien Geron that can be found here:

https://github.com/ageron/handson-ml/blob/master/math_linear_algebra.ipynb

# Matrices with Python
First, NumPy and Matplotlib need to be imported. Matplotlib needs to be made inline for the notebook, and seaborn needs to be imported to make the plots look prettier.

Note that the 3D toolkit of Matplotlib is being imported.

In [1]:
%matplotlib inline

import matplotlib.pyplot as plt
import seaborn as sns

from mpl_toolkits.mplot3d import Axes3D

import numpy as np
import numpy.linalg as la

As in the vectors notebook, seaborn will be used to pretty up any plots.

In [3]:
sns.set(style='whitegrid', palette='muted', font='roboto')
sns.set_context('talk')

Most matrices used throughout this notebook will now be defined. They are as follows:
- A: square matrix in $\rm I\!R^3$
- B: square matrix in $\rm I\!R^3$
- C: square matrix in $\rm I\!R^3$
- D: upper triangular matrix in $\rm I\!R^3$
- E: lower triangular matrix in $\rm I\!R^3$
- F: diagonal matrix in $\rm I\!R^3$
- G: 3x2 matrix
- H: 2x3 matrix
- I: Identity matrix in $\rm I\!R^3$
- J: 5x4 matrix
- K: 4x6 matrix
- L: 2x5 matrix
- M: 6x1 matrix

In [5]:
A = np.array([
    [2,4,1],
    [6,4,3],
    [4,1,2],
])
B = np.array([
    [7,5,2],
    [0,1,0],
    [5,5,5],
])
C = np.array([
    [4,2,5],
    [6,5,2],
    [8,2,3],
])
D = np.array([
    [4,5,7],
    [0,5,1],
    [0,0,3],
])
E = np.array([
    [4,0,0],
    [6,2,0],
    [4,2,3],
])
F = np.array([
    [4,0,0],
    [0,7,0],
    [0,0,3],
])
G = np.array([
    [2,2],
    [3,1],
    [6,3],
])
H = np.array([
    [7,5,3],
    [2,1,3],
])
I = np.eye(3)
J = np.array([
    [4,3,2,1],
    [2,4,3,5],
    [6,4,7,2],
    [1,3,5,2],
    [3,3,4,4],
])
K = np.array([
    [2,1,3,4,2,5],
    [4,3,5,6,1,2],
    [4,7,2,3,1,1],
    [3,2,5,4,6,3],
])
L = np.array([
    [4,6,2,7,6],
    [3,2,3,3,1],
])
M = np.array([
    [1],
    [5],
    [4],
    [3],
    [5],
    [9],
])

In [6]:
print(f'Shape of A: {A.shape}')
print(f'Shape of J: {J.shape}')
print(f'Shape of M: {M.shape}')

Shape of A: (3, 3)
Shape of J: (5, 4)
Shape of M: (6, 1)


In [9]:
print(f'3D Square Matrix:\n{A}')

3D Square Matrix:
[[2 4 1]
 [6 4 3]
 [4 1 2]]


In [10]:
print(f'3D Upper Triangular Matrix:\n{D}')
print(f'\n3D Lower Triangular Matrix:\n{E}')

3D Upper Triangular Matrix:
[[4 5 7]
 [0 5 1]
 [0 0 3]]
3D Lower Triangular Matrix:
[[4 0 0]
 [6 2 0]
 [4 2 3]]


In [11]:
print(f'3D Diagonal Matrix:\n{F}')

3D Diagonal Matrix:
[[4 0 0]
 [0 7 0]
 [0 0 3]]


In [8]:
print(f'3D Identity Matrix:\n{I}')

3D Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Matrix Addition
Matrix addition can only be done with two matrices of the same size $m\times{n}$. The sum of two matrices of size $m\times{n}$ results in a third matrix of size $m\times{n}$ in which each element equals the sum of the corresponding elements in the original two matrices. So, $C_{i,j} = A_{i,j} + B_{i,j}$.

In [17]:
print(f'A:\n{A}')
print(f'B:\n{B}')
print(f'A+B:\n{A+B}')

A:
[[2 4 1]
 [6 4 3]
 [4 1 2]]
B:
[[7 5 2]
 [0 1 0]
 [5 5 5]]
A+B:
[[9 9 3]
 [6 5 3]
 [9 6 7]]


It exhibits the following properties:

In [18]:
print('Matrix of any size:')
print(f'K + K =\n{K + K}')

print('\nCommutative:')
print(f'A + B =\n{A + B}')
print(f'\nB + A =\n{B + A}')

print('\nAssociative:')
print(f'A + (B + C) =\n{A + (B + C)}')
print(f'\n(A + B) +C =\n{(A + B) + C}')

print('\nMust belong to the same set of valued tuples:')
try:
    print(f'A + K =')
    A + K
except Exception as e:
    print(e)

Matrix of any size:
K + K =
[[ 4  2  6  8  4 10]
 [ 8  6 10 12  2  4]
 [ 8 14  4  6  2  2]
 [ 6  4 10  8 12  6]]

Commutative:
A + B =
[[9 9 3]
 [6 5 3]
 [9 6 7]]

B + A =
[[9 9 3]
 [6 5 3]
 [9 6 7]]

Associative:
A + (B + C) =
[[13 11  8]
 [12 10  5]
 [17  8 10]]

(A + B) +C =
[[13 11  8]
 [12 10  5]
 [17  8 10]]

Must belong to the same set of valued tuples:
A + K =
operands could not be broadcast together with shapes (3,3) (4,6) 


## Matrix Multiplication
There are two primary ways in which matrices are multiplied: Scalar Multiplication and Matrix Multiplication.

### Scalar Multiplication
Multiplying a matrix by a scalar is equivalent to multiplying each element in the matrix by that same scalar.

In [13]:
scalar = 3
print(f'A:\n{A}')
print(f'\nscalar * A:\n{scalar*A}')

A:
[[2 4 1]
 [6 4 3]
 [4 1 2]]

scalar * A:
[[ 6 12  3]
 [18 12  9]
 [12  3  6]]


It exhibits the following properties:

In [14]:
print('Matrix of any size:')
print(f'{scalar} * K =\n{scalar * K}')
print(f'\n{scalar} * M =\n{scalar * M}')

print('\nCommutative:')
print(f'{scalar} * A =\n{scalar * A}')
print(f'\nA * {scalar} =\n{A * scalar}')

print('\nAssociative:')
print(f'{scalar} * ({scalar} * A) =\n{scalar * (scalar * A)}')
print(f'\n({scalar} * {scalar}) * A =\n{(scalar * scalar) * A}')

print('\nDistributive:')
print(f'{scalar} * (A + B) =\n{scalar * (A + B)}')
print(f'\n({scalar} * A) + ({scalar} * B) =\n{(scalar * A) + (scalar * B)}')

Matrix of any size:
3 * K =
[[ 6  3  9 12  6 15]
 [12  9 15 18  3  6]
 [12 21  6  9  3  3]
 [ 9  6 15 12 18  9]]

3 * M =
[[ 3]
 [15]
 [12]
 [ 9]
 [15]
 [27]]

Commutative:
3 * A =
[[ 6 12  3]
 [18 12  9]
 [12  3  6]]

A * 3 =
[[ 6 12  3]
 [18 12  9]
 [12  3  6]]

Associative:
3 * (3 * A) =
[[18 36  9]
 [54 36 27]
 [36  9 18]]

(3 * 3) * A =
[[18 36  9]
 [54 36 27]
 [36  9 18]]

Distributive:
3 * (A + B) =
[[27 27  9]
 [18 15  9]
 [27 18 21]]

(3 * A) + (3 * B) =
[[27 27  9]
 [18 15  9]
 [27 18 21]]


### Matrix Multiplication
Matrix multiplication, like matrix addition, can only be done with matrices of particular sizes. For a matrix multiplication to occur between __A__ and **B**, <b>A</b> must be of size $m\times{n}$, and <b>B</b> must be of size $n\times{k}$. The resulting matrix is of size $m\times{k}$. Each element in the resulting matrix is equal to the dot product of <b>A</b>'s row vectors $R_i$ up to $i=n$ and <b>B</b>'s column vectors $C_i$ up to $i=n$. It is better represented by:

$$
\left[\matrix{
A_{11}B_{11}+A_{12}B_{21}+\cdots +A_{1n}B_{n1} & A_{11}B_{12}+A_{12}B_{22}+\cdots +A_{1n}B_{n2} & \ldots & A_{11}B_{1k}+A_{12}B_{2k}+\cdots +A_{1n}B_{nk} \cr
A_{21}B_{11}+A_{22}B_{21}+\cdots +A_{2n}B_{n1} & A_{21}B_{12}+A_{22}B_{22}+\cdots +A_{2n}B_{n2} & \ldots & A_{21}B_{1k}+A_{22}B_{2k}+\cdots +A_{2n}B_{nk} \cr
\vdots & \vdots & \ddots & \vdots \cr
A_{m1}B_{11}+A_{m2}B_{21}+\cdots +A_{mn}B_{n1} & A_{m1}B_{12}+A_{m2}B_{22}+\cdots +A_{mn}B_{n2} & \ldots & A_{m1}B_{1k}+A_{m2}B_{2k}+\cdots +A_{mn}B_{nk}
}\right]
$$

It's much easier to understand with examples. As with vector dot products, numpy offers 2 functions for matrix multiplications, as well as the infix operator ('@') introduced in Python 3.5.

In [35]:
print(A)

[[2 4 1]
 [6 4 3]
 [4 1 2]]


In [36]:
print(B)

[[7 5 2]
 [0 1 0]
 [5 5 5]]


In [34]:
print(A@B)
print(A.dot(B))
print(np.dot(A,B))
print(np.matmul(A,B))

[[19 19  9]
 [57 49 27]
 [38 31 18]]
[[19 19  9]
 [57 49 27]
 [38 31 18]]
[[19 19  9]
 [57 49 27]
 [38 31 18]]
[[19 19  9]
 [57 49 27]
 [38 31 18]]


In [37]:
print('Element 2,1 in A multiplied by B:')
print(f'{A[1][0]*B[0][0]+A[1][1]*B[1][0]+A[1][2]*B[2][0]} == {(A@B)[1][0]}')

Element 2,1 in A multiplied by B:
57 == 57


In [44]:
print('Not Commutative:')
print(f'J * K =\n{J@K}')
try:
    print(f'K * J =')
    K@J
except Exception as e:
    print(e)

print('\nAssociative:')
print(f'J * (K * M) =\n{J @ (K @ M)}')
print(f'\n(J * K) * M =\n{(J @ K) @ M}')
    
print('\nAssociative for Scalar Multiplication:')
print(f'{scalar} * (J * K) =\n{scalar * (J @ K)}')
print(f'\n({scalar} * J) * K =\n{(scalar * J) @ K}')

print('\nDistributive for Matrix Addition:')
print(f'H * (A + B) =\n{H @ (A + B)}')
print(f'\n(H * A) + (H * B) =\n{(H @ A) + (H @ B)}')

Not Commutative:
J * K =
[[31 29 36 44 19 31]
 [47 45 57 61 41 36]
 [62 71 62 77 35 51]
 [40 49 38 45 22 22]
 [46 48 52 58 37 37]]
K * J =
shapes (4,6) and (5,4) not aligned: 6 (dim 1) != 5 (dim 0)

Associative:
J * (K * M) =
[[ 826]
 [1212]
 [1530]
 [ 880]
 [1186]]

(J * K) * M =
[[ 826]
 [1212]
 [1530]
 [ 880]
 [1186]]

Associative for Scalar Multiplication:
3 * (J * K) =
[[ 93  87 108 132  57  93]
 [141 135 171 183 123 108]
 [186 213 186 231 105 153]
 [120 147 114 135  66  66]
 [138 144 156 174 111 111]]

(3 * J) * K =
[[ 93  87 108 132  57  93]
 [141 135 171 183 123 108]
 [186 213 186 231 105 153]
 [120 147 114 135  66  66]
 [138 144 156 174 111 111]]

Distributive for Matrix Addition:
H * (A + B) =
[[120 106  57]
 [ 51  41  30]]

(H * A) + (H * B) =
[[120 106  57]
 [ 51  41  30]]
